FROM node:19-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --silent

# Copy the rest of the app files
COPY . .

# Expose port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
