services:
  db:
    container_name: ASO-DB
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the initialization script
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  spring-boot-app:
    container_name: ASO-API
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - .env:/app/.env
      - ~/.aws:/root/.aws  # Mount the AWS credentials file
    networks:
      - db
    depends_on:
      - db

  react-app:
    container_name: REACT-APP
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - spring-boot-app

networks:
  db:
    driver: bridge

volumes:
  db:
