spring:
  config:
    import: optional:file:.env[.properties] # Development properties
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5332/aso # docker
#    url: jdbc:p6spy:postgresql://localhost:5432/aso # local
#    url: jdbc:p6spy:postgresql://db:5432/aso # both inside docker
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: postgres
    password: ${POSTGRES_PASSWORD}  # Reference the POSTGRES_PASSWORD variable
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        default_batch_fetch_size: 20 # n+1
    show-sql: false # because p6spy is logging
  flyway:
    default-schema: public
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB

server:
  port: 8081
  error:
    include-message: always

aws:
  region: eu-central-1
  s3:
    buckets:
      servicesBucket: aso-services-143207520

#logging:
#  level:
#    org:
#      hibernate:
#        orm.jdbc.bind: trace
##        SQL: debug
