spring:
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5332/aso # docker
    #url: jdbc:postgresql://localhost:5432/aso # local
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true
  flyway:
    default-schema: public
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB

logging:
  level:
    org:
      hibernate:
        orm.jdbc.bind: trace
#        SQL: debug

server:
  port: 8081
  error:
    include-message: always
